image:
  - Visual Studio 2015
  - ubuntu

# Defaults to MSBuild
build: off

for:
-
  matrix:
    only:
      - image: ubuntu
  clone_folder: /usr/go/src/github.com/adamdecaf/cert-manage
  environment:
    GOPATH: /usr/go/  
-
  matrix:
    only:
      - image: Visual Studio 2015  
  clone_folder: c:\gopath\src\github.com\adamdecaf\cert-manage

  environment:
    GOPATH: c:\gopath
    CGO_ENABLED: '1'
    GOOS: windows
    GOARCH: amd64
    DEBUG: true

stack: go 1.10, docker

services:
  - docker

before_test:
  - go vet ./...
  - go fmt ./...
  - go build -o bin/cert-manage-amd64.exe github.com/adamdecaf/cert-manage

test_script:
  - go test -test.parallel 8 ./...
